wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1657135635
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 16
      - 17
      4: 3.10.4
      5: 0.12.21
      8:
      - 3
      - 5
      10:
      - 3
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 32
classes:
  desc: null
  value: 37
data_split_ratio:
  desc: null
  value: 0.7
dataset:
  desc: null
  value: STANFORD_DOGS
epochs:
  desc: null
  value: 50
image_size:
  desc: null
  value:
  - 64
  - 64
learning_rate:
  desc: null
  value: 0.005
run_name:
  desc: null
  value: pretrained-resnet18-stanford-dogs
